### ISSUE TITLE
ValueError: All arrays must be of the same length

### ISSUE THREAD

**Issue by agroppi** [ozanozisik/orsum#9]
Hi,

I'm trying to use orsum on multiple enrichment results.
My command : 
`python3 orsum.py --gmt 'hsapiens.GO_BP.name.gmt' --files 'AGS_KO_vs_AGS_WT_GOBP.txt' 'MKN74_KO_vs_AGS_KO_GOBP.txt' 'MKN74_KO_vs_HFE_KO_GOBP.txt' 'AGS_KO_vs_AGS_WT_GOBP.txt' --fileAliases 'AGS_KO_vs_AGS_WT' 'MKN74_KO_vs_AGS_KO' 'MKN74_KO_vs_HFE_KO' 'AGS_KO_vs_AGS_WT' --outputFolder 'OutputGOBP'`

I'm facing the following error : 
`Traceback (most recent call last):
  File "/isilon/home/ag/orsum/bin/orsum.py", line 199, in <module>
    writeTermSummaryFileClustered(termSummary, termIdToGenesDict, termIdToTermNameDict, termIdsListList, fileAliases, fileName+'-SummaryClustered.tsv', numberOfTermsToPlot)
  File "/isilon/home/ag/orsum/bin/termCombinationLib.py", line 405, in writeTermSummaryFileClustered
    dfRanksPerInputFile=pd.DataFrame.from_dict(ranksPerInputFile)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/isilon/home/ag/orsum/lib/python3.11/site-packages/pandas/core/frame.py", line 1764, in from_dict
    return cls(data, index=index, columns=columns, dtype=dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/isilon/home/ag/orsum/lib/python3.11/site-packages/pandas/core/frame.py", line 664, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/isilon/home/ag/orsum/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 493, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/isilon/home/ag/orsum/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 118, in arrays_to_mgr
    index = _extract_index(arrays)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/isilon/home/ag/orsum/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 666, in _extract_index
    raise ValueError("All arrays must be of the same length")
ValueError: All arrays must be of the same length
`

Here are the input files : 
[orsum_input_files.zip](https://github.com/ozanozisik/orsum/files/11665576/orsum_input_files.zip)

Thanks for tour help

AG

**Comment by agroppi** [comment]
Arghhh sorry for bothering you with such a stupid misstake ;)
Thanks
